### ISSUE TITLE
Error "Failed to download manifest"

### ISSUE THREAD

**Issue by krmr** [sle118/squeezelite-esp32-installer#27]
When trying to install on a ESP Muse Luxe I received a error message reading "Failed to download manifest".

From looking into the browser console a request to https://sle118.github.io/squeezelite-esp32-installer/base_manifest.json fails with 404.
Before that there are also other errors, especially "main.js:159 Unable to set manifest for platform SqueezeAmp: TypeError: Cannot read properties of undefined (reading 'manifest')".

Looking into the artifacts repository it looks to me like there are only files for SqueezeAmp while those for I2S and Muse were deleted with the most recent commit.

**Comment by krmr** [comment]
Looks like some later update of the images resolved the issue.

**Comment by sle118** [comment]
@krmr thank you for reporting this. We had to remove ones of the releases from the main project since it had introduced an issue which caused console and GUI to malfunction
